export const INVITE_CODE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours
export const MAX_INVITE_ATTEMPTS = 5;
export const ACTIVE_SPACE_CONFLICT_MESSAGE = "You already belong to an active space.";
export const ACTIVE_SPACE_MEMBER_INDEX = "space_members_active_user_unique";
export const ACTIVE_SPACE_ROLE_INDEX = "space_members_active_space_role_unique";
export const ACTIVE_INVITE_CODE_INDEX = "spaces_active_invite_code_unique";
export const USER_ID_COLUMN = "user_id";
export const INVITE_CODE_COLUMN = "invite_code";
export const PRISMA_UNIQUE_CONSTRAINT_ERROR = "P2002";
export const JOIN_FAILURE_LIMIT = 5;
export const JOIN_WINDOW = "10 m";
export const JOIN_LOCK_SECONDS = 600;
export const JOIN_LOCK_MESSAGE = "Too many join attempts. Try again in 10 minutes.";
