create table if not exists public.spaces (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  invite_code text,
  invite_code_expires_at timestamptz,
  is_active boolean not null default true,
  created_by_user_id uuid not null references public.users(id) on delete restrict,
  updated_by_user_id uuid not null references public.users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint spaces_name_length_check
    check (char_length(btrim(name)) between 2 and 100),

  constraint spaces_invite_code_format_check
    check (
      invite_code is null
      or invite_code ~ '^[a-z]{3}[a-z2-9]{5}$'
    )
);

create unique index if not exists spaces_active_invite_code_unique_idx
  on public.spaces (invite_code)
  where is_active = true and invite_code is not null;

create index if not exists spaces_is_active_idx
  on public.spaces (is_active);

create index if not exists spaces_created_by_user_id_idx
  on public.spaces (created_by_user_id);

create index if not exists spaces_updated_by_user_id_idx
  on public.spaces (updated_by_user_id);

create index if not exists spaces_created_at_idx
  on public.spaces (created_at desc);

drop trigger if exists set_spaces_updated_at on public.spaces;
create trigger set_spaces_updated_at
before update on public.spaces
for each row
execute function public.set_updated_at();
