create table if not exists public.space_members (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  display_name text not null,
  role public.space_member_role not null,
  is_active boolean not null default true,
  onboarding_completed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint space_members_display_name_length_check
    check (char_length(btrim(display_name)) between 2 and 100)
);

create unique index if not exists space_members_active_user_unique_idx
  on public.space_members (user_id)
  where is_active = true;

create unique index if not exists space_members_active_space_user_unique_idx
  on public.space_members (space_id, user_id)
  where is_active = true;

create index if not exists space_members_space_id_idx
  on public.space_members (space_id);

create index if not exists space_members_user_id_idx
  on public.space_members (user_id);

create index if not exists space_members_role_idx
  on public.space_members (role);

create index if not exists space_members_is_active_idx
  on public.space_members (is_active);

drop trigger if exists set_space_members_updated_at on public.space_members;
create trigger set_space_members_updated_at
before update on public.space_members
for each row
execute function public.set_updated_at();
